### ISSUE TITLE
GOG plugin, unable to complete setup

### ISSUE THREAD

**Issue by jdengle** [suchmememanyskill/Alfae#13]
After logging into GOG and being redirected to a blank page, I copy the URL and then paste into the box, and it says "You seemingly did not put in the right URL"

The URL looks like https://embed.gog.com/on_login_success?origin=client&code=...

**Comment by suchmememanyskill** [comment]
Thanks for reporting,
I think the issue is pasting with the right click menu does not register a keystroke, so internally the value of the textbox is never applied.

**Comment by suchmememanyskill** [comment]
Can you try this build? https://github.com/suchmememanyskill/Alfae/actions/runs/2682998529

**Comment by suchmememanyskill** [comment]
Made a new release, seems to work on my end. Thanks again for reporting
