### ISSUE TITLE
Can't export to Steam in Windows

### ISSUE THREAD

**Issue by deniscerri** [suchmememanyskill/Alfae#26]
Using Local and Epic Games

App doesn't show any error and says they were added but nothing shows up on steam. I can manually add on steam and they show up.
Am i doing something wrong?

https://user-images.githubusercontent.com/64997243/213935905-69cf1f1a-d9a0-4460-afed-707a44092060.mp4

**Comment by deniscerri** [comment]
Restarted the pc then it worked

**Comment by suchmememanyskill** [comment]
You need to restart steam for them to show up, maybe i should make that more clear
