### ISSUE TITLE
Build instructions.

### ISSUE THREAD

**Issue by begin-theadventure** [suchmememanyskill/Alfae#30]
Would it be possible to add instructions for building from the source code?

**Comment by suchmememanyskill** [comment]
To make a debug build, running the solution(building all then running Launcher) would be sufficient.

For how to construct a release, see the github actions workflow file

**Comment by begin-theadventure** [comment]
Thanks! The workflow files were the solution.
Although while I had fun building this, I noticed rather unnecessary commands:
`dotnet restore` and `mkdir -p Release/plugins` - `dotnet publish` takes care of both.

**Comment by begin-theadventure** [comment]
Thanks! The workflow file was the solution.
Although while I had fun building this, I noticed rather unnecessary commands:
`dotnet restore` and `mkdir -p Release/plugins` - `dotnet publish` takes care of both.
